// Generated by gencpp from file pkg/Num.msg
// DO NOT EDIT!


#ifndef PKG_MESSAGE_NUM_H
#define PKG_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : sapaan()
    , angka(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : sapaan(_alloc)
    , angka(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sapaan_type;
  _sapaan_type sapaan;

   typedef uint32_t _angka_type;
  _angka_type angka;





  typedef boost::shared_ptr< ::pkg::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::pkg::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::pkg::Num > NumPtr;
typedef boost::shared_ptr< ::pkg::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg::Num_<ContainerAllocator1> & lhs, const ::pkg::Num_<ContainerAllocator2> & rhs)
{
  return lhs.sapaan == rhs.sapaan &&
    lhs.angka == rhs.angka;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg::Num_<ContainerAllocator1> & lhs, const ::pkg::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pkg::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5beac8738af3e03cbb4e6e63243bec98";
  }

  static const char* value(const ::pkg::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5beac8738af3e03cULL;
  static const uint64_t static_value2 = 0xbb4e6e63243bec98ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg/Num";
  }

  static const char* value(const ::pkg::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sapaan\n"
"uint32 angka\n"
;
  }

  static const char* value(const ::pkg::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sapaan);
      stream.next(m.angka);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg::Num_<ContainerAllocator>& v)
  {
    s << indent << "sapaan: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sapaan);
    s << indent << "angka: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.angka);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_MESSAGE_NUM_H
