// Generated by gencpp from file pkg/pertambahanResponse.msg
// DO NOT EDIT!


#ifndef PKG_MESSAGE_PERTAMBAHANRESPONSE_H
#define PKG_MESSAGE_PERTAMBAHANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg
{
template <class ContainerAllocator>
struct pertambahanResponse_
{
  typedef pertambahanResponse_<ContainerAllocator> Type;

  pertambahanResponse_()
    : sum(0)  {
    }
  pertambahanResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::pkg::pertambahanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg::pertambahanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pertambahanResponse_

typedef ::pkg::pertambahanResponse_<std::allocator<void> > pertambahanResponse;

typedef boost::shared_ptr< ::pkg::pertambahanResponse > pertambahanResponsePtr;
typedef boost::shared_ptr< ::pkg::pertambahanResponse const> pertambahanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg::pertambahanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg::pertambahanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pkg::pertambahanResponse_<ContainerAllocator1> & lhs, const ::pkg::pertambahanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pkg::pertambahanResponse_<ContainerAllocator1> & lhs, const ::pkg::pertambahanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pkg::pertambahanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg::pertambahanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg::pertambahanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg::pertambahanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg::pertambahanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg::pertambahanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg::pertambahanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::pkg::pertambahanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg::pertambahanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg/pertambahanResponse";
  }

  static const char* value(const ::pkg::pertambahanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg::pertambahanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
;
  }

  static const char* value(const ::pkg::pertambahanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg::pertambahanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pertambahanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg::pertambahanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg::pertambahanResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_MESSAGE_PERTAMBAHANRESPONSE_H
