// Generated by gencpp from file pkg/pertambahan.msg
// DO NOT EDIT!


#ifndef PKG_MESSAGE_PERTAMBAHAN_H
#define PKG_MESSAGE_PERTAMBAHAN_H

#include <ros/service_traits.h>


#include <pkg/pertambahanRequest.h>
#include <pkg/pertambahanResponse.h>


namespace pkg
{

struct pertambahan
{

typedef pertambahanRequest Request;
typedef pertambahanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pertambahan
} // namespace pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg::pertambahan > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::pkg::pertambahan&) { return value(); }
};

template<>
struct DataType< ::pkg::pertambahan > {
  static const char* value()
  {
    return "pkg/pertambahan";
  }

  static const char* value(const ::pkg::pertambahan&) { return value(); }
};


// service_traits::MD5Sum< ::pkg::pertambahanRequest> should match
// service_traits::MD5Sum< ::pkg::pertambahan >
template<>
struct MD5Sum< ::pkg::pertambahanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::pertambahan >::value();
  }
  static const char* value(const ::pkg::pertambahanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::pertambahanRequest> should match
// service_traits::DataType< ::pkg::pertambahan >
template<>
struct DataType< ::pkg::pertambahanRequest>
{
  static const char* value()
  {
    return DataType< ::pkg::pertambahan >::value();
  }
  static const char* value(const ::pkg::pertambahanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg::pertambahanResponse> should match
// service_traits::MD5Sum< ::pkg::pertambahan >
template<>
struct MD5Sum< ::pkg::pertambahanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::pertambahan >::value();
  }
  static const char* value(const ::pkg::pertambahanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::pertambahanResponse> should match
// service_traits::DataType< ::pkg::pertambahan >
template<>
struct DataType< ::pkg::pertambahanResponse>
{
  static const char* value()
  {
    return DataType< ::pkg::pertambahan >::value();
  }
  static const char* value(const ::pkg::pertambahanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_MESSAGE_PERTAMBAHAN_H
